version: "3.9"

services:
  postgres:
    image: postgres:15-bookworm
    container_name: payouts_db
    restart: always
    environment:
      POSTGRES_DB: payout
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
